// Mock dataset (Planejado foi preenchido onde era N/A ou 0 com metas plausíveis e conservadoras)
// Regra aplicada: Planejado ≈ Executado * (1.06 a 1.10) conforme escala; quando Executado=0, Planejado=0.
// Estrutura: { dept, group, indicator, unit, s1:{planned, executed}, s2:{planned, executed} }

const MOCK_DATA = [
  // ---------------- GDA ----------------
  { dept:"GDA", group:"PNEFA", indicator:"Vigilâncias Ativas para Febre Aftosa", unit:"qtd",
    s1:{ planned:419, executed:419 }, s2:{ planned:419, executed:379 } },

  { dept:"GDA", group:"PNCEBT", indicator:"Vigilância Clínica Pós Ocorrência de Tuberculose nos Abatedouros", unit:"qtd",
    s1:{ planned:19, executed:18 }, s2:{ planned:7, executed:6 } },
  { dept:"GDA", group:"PNCEBT", indicator:"Fiscalização em Sala de Testes de Médico Veterinário Habilitado", unit:"qtd",
    s1:{ planned:20, executed:3 }, s2:{ planned:20, executed:5 } },

  { dept:"GDA", group:"PNSE", indicator:"Interdições de estabelecimentos/propriedades p/ investigação de AIE e/ou Mormo", unit:"qtd",
    s1:{ planned:17, executed:16 }, s2:{ planned:6, executed:5 } },
  { dept:"GDA", group:"PNSE", indicator:"Envios de amostras biológicas a laboratórios oficiais", unit:"qtd",
    s1:{ planned:8, executed:7 }, s2:{ planned:5, executed:4 } },
  { dept:"GDA", group:"PNSE", indicator:"Amostras biológicas de equídeos (investigação AIE/Mormo)", unit:"qtd",
    s1:{ planned:159, executed:150 }, s2:{ planned:159, executed:150 } },
  { dept:"GDA", group:"PNSE", indicator:"Eutanásias / sacrifícios sanitários (AIE/Mormo)", unit:"qtd",
    s1:{ planned:17, executed:16 }, s2:{ planned:11, executed:10 } },
  { dept:"GDA", group:"PNSE", indicator:"Equídeos testados (exames oficiais AIE/Mormo)", unit:"qtd",
    s1:{ planned:181, executed:171 }, s2:{ planned:110, executed:102 } },
  { dept:"GDA", group:"PNSE", indicator:"Cadastro de propriedades com equídeos (novos e atualizações)", unit:"qtd",
    s1:{ planned:348, executed:147 }, s2:{ planned:348, executed:26 } },
  { dept:"GDA", group:"PNSE", indicator:"Vigilâncias ativas em propriedades com equídeos", unit:"qtd",
    s1:{ planned:291, executed:38 }, s2:{ planned:291, executed:5 } },

  // PNSA (tinha planejado=0 -> meta plausível baseada no executado)
  { dept:"GDA", group:"PNSA", indicator:"Registros/renovação de estabelecimentos avícolas comerciais emitidos", unit:"qtd",
    s1:{ planned:32, executed:29 }, s2:{ planned:40, executed:36 } },
  { dept:"GDA", group:"PNSA", indicator:"Requerimentos protocolados para registro de estabelecimento avícola", unit:"qtd",
    s1:{ planned:13, executed:12 }, s2:{ planned:13, executed:12 } },
  { dept:"GDA", group:"PNSA", indicator:"Cadastro de estabelecimentos comercializadores de aves vivas", unit:"qtd",
    s1:{ planned:0, executed:0 }, s2:{ planned:44, executed:40 } },
  { dept:"GDA", group:"PNSA", indicator:"Atendimentos à suspeita de SRN (aves)", unit:"qtd",
    s1:{ planned:9, executed:8 }, s2:{ planned:8, executed:7 } },

  // PNSAA
  { dept:"GDA", group:"PNSAA", indicator:"Total de animais fiscalizados", unit:"qtd",
    s1:{ planned:0, executed:0 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"PNSAA", indicator:"Número de propriedades cadastradas", unit:"qtd",
    s1:{ planned:300, executed:11 }, s2:{ planned:300, executed:16 } },

  // PNSAp (tinha alguns planejados 0 -> meta plausível)
  { dept:"GDA", group:"PNSAp", indicator:"Número de vigilância ativa", unit:"qtd",
    s1:{ planned:288, executed:5 }, s2:{ planned:288, executed:14 } },
  { dept:"GDA", group:"PNSAp", indicator:"Número de propriedades fiscalizadas", unit:"qtd",
    s1:{ planned:6, executed:5 }, s2:{ planned:16, executed:14 } },
  { dept:"GDA", group:"PNSAp", indicator:"Número de propriedades cadastradas", unit:"qtd",
    s1:{ planned:288, executed:5 }, s2:{ planned:288, executed:33 } },
  { dept:"GDA", group:"PNSAp", indicator:"Número de colmeias cadastradas", unit:"qtd",
    s1:{ planned:31, executed:28 }, s2:{ planned:356, executed:324 } },

  // PNSS (tinha planejados 0 -> meta plausível)
  { dept:"GDA", group:"PNSS", indicator:"Cadastros de propriedades", unit:"qtd",
    s1:{ planned:200, executed:28 }, s2:{ planned:200, executed:324 } },
  { dept:"GDA", group:"PNSS", indicator:"Fiscalização em lixões", unit:"qtd",
    s1:{ planned:12, executed:80 }, s2:{ planned:12, executed:35 } },
  { dept:"GDA", group:"PNSS", indicator:"Vigilância clínica (nº de propriedades)", unit:"qtd",
    s1:{ planned:520, executed:132 }, s2:{ planned:520, executed:397 } },
  { dept:"GDA", group:"PNSS", indicator:"Vigilância clínica (nº de animais inspecionados)", unit:"qtd",
    s1:{ planned:5000, executed:309 }, s2:{ planned:5000, executed:4746 } },
  { dept:"GDA", group:"PNSS", indicator:"Vigilância sorológica (nº de propriedades na ZL de PSC)", unit:"qtd",
    s1:{ planned:131, executed:123 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"PNSS", indicator:"Vigilância sorológica (nº de amostras coletadas na ZL de PSC)", unit:"qtd",
    s1:{ planned:0, executed:0 }, s2:{ planned:0, executed:0 } },

  // PNCRH (tinha planejados 0 -> meta plausível)
  { dept:"GDA", group:"PNCRH", indicator:"Abrigos de morcegos hematófagos cadastrados", unit:"qtd",
    s1:{ planned:4, executed:4 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"PNCRH", indicator:"Morcegos hematófagos capturados", unit:"qtd",
    s1:{ planned:58, executed:54 }, s2:{ planned:26, executed:24 } },
  { dept:"GDA", group:"PNCRH", indicator:"Morcegos enviados para laboratório", unit:"qtd",
    s1:{ planned:0, executed:0 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"PNCRH", indicator:"Notificações de suspeita de síndrome nervosa", unit:"qtd",
    s1:{ planned:4, executed:4 }, s2:{ planned:4, executed:4 } },
  { dept:"GDA", group:"PNCRH", indicator:"Atendimentos às notificações de suspeita", unit:"qtd",
    s1:{ planned:4, executed:4 }, s2:{ planned:4, executed:4 } },
  { dept:"GDA", group:"PNCRH", indicator:"Coleta/envio de material encefálico ao laboratório", unit:"qtd",
    s1:{ planned:2, executed:2 }, s2:{ planned:3, executed:3 } },
  { dept:"GDA", group:"PNCRH", indicator:"Herbívoros vacinados contra raiva", unit:"qtd",
    s1:{ planned:525711, executed:482511 }, s2:{ planned:334859, executed:307210 } },
  { dept:"GDA", group:"PNCRH", indicator:"Propriedades com vacinação", unit:"qtd",
    s1:{ planned:5343, executed:4852 }, s2:{ planned:11184, executed:10168 } },
  { dept:"GDA", group:"PNCRH", indicator:"Total de propriedades com utilização de pasta vampiricida", unit:"qtd",
    s1:{ planned:0, executed:0 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"PNCRH", indicator:"Municípios com vacinação antirrábica obrigatória", unit:"qtd",
    s1:{ planned:6, executed:38 }, s2:{ planned:6, executed:47 } },

  // EPIDEMIOLOGIA (N/A -> metas plausíveis)
  { dept:"GDA", group:"EPIDEMIOLOGIA", indicator:"Notificações - Sisbravet", unit:"qtd",
    s1:{ planned:33, executed:31 }, s2:{ planned:25, executed:23 } },
  { dept:"GDA", group:"EPIDEMIOLOGIA", indicator:"Ocorrências - Sisbravet", unit:"qtd",
    s1:{ planned:33, executed:31 }, s2:{ planned:25, executed:23 } },
  { dept:"GDA", group:"EPIDEMIOLOGIA", indicator:"Verificações por atendimento - Sisbravet", unit:"qtd",
    s1:{ planned:60, executed:56 }, s2:{ planned:21, executed:19 } },
  { dept:"GDA", group:"EPIDEMIOLOGIA", indicator:"Elaboração de documentos técnicos", unit:"qtd",
    s1:{ planned:28, executed:26 }, s2:{ planned:14, executed:13 } },
  { dept:"GDA", group:"EPIDEMIOLOGIA", indicator:"Solicitações de correções", unit:"qtd",
    s1:{ planned:32, executed:30 }, s2:{ planned:10, executed:9 } },
  { dept:"GDA", group:"EPIDEMIOLOGIA", indicator:"Reuniões ministradas pelo setor", unit:"qtd",
    s1:{ planned:3, executed:3 }, s2:{ planned:1, executed:1 } },
  { dept:"GDA", group:"EPIDEMIOLOGIA", indicator:"Participação em capacitações/reuniões MAPA", unit:"qtd",
    s1:{ planned:9, executed:8 }, s2:{ planned:4, executed:4 } },
  { dept:"GDA", group:"EPIDEMIOLOGIA", indicator:"Triagem amostras", unit:"qtd",
    s1:{ planned:8, executed:8 }, s2:{ planned:6, executed:5 } },

  // AUTOS DE INFRAÇÃO (0 -> metas plausíveis)
  { dept:"GDA", group:"AUTOS DE INFRAÇÃO", indicator:"Número de autos emitidos", unit:"qtd",
    s1:{ planned:340, executed:309 }, s2:{ planned:11, executed:10 } },
  { dept:"GDA", group:"AUTOS DE INFRAÇÃO", indicator:"Autos emitidos por trânsito irregular", unit:"qtd",
    s1:{ planned:40, executed:36 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"AUTOS DE INFRAÇÃO", indicator:"Autos emitidos por não vacinação do rebanho", unit:"qtd",
    s1:{ planned:8, executed:7 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"AUTOS DE INFRAÇÃO", indicator:"Infração por não comunicação da vacina", unit:"qtd",
    s1:{ planned:0, executed:0 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"AUTOS DE INFRAÇÃO", indicator:"Autos emitidos por não declaração durante a campanha", unit:"qtd",
    s1:{ planned:304, executed:276 }, s2:{ planned:11, executed:10 } },

  // INSUMOS VETERINÁRIOS
  { dept:"GDA", group:"INSUMOS VETERINÁRIOS", indicator:"Número de revendas agropecuárias credenciadas", unit:"qtd",
    s1:{ planned:0, executed:0 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"INSUMOS VETERINÁRIOS", indicator:"Total de doses de vacinas apreendidas", unit:"qtd",
    s1:{ planned:0, executed:0 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"INSUMOS VETERINÁRIOS", indicator:"Total de doses de vacinas destruídas", unit:"qtd",
    s1:{ planned:0, executed:0 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"INSUMOS VETERINÁRIOS", indicator:"Doses de vacinas comercializadas", unit:"qtd",
    s1:{ planned:22415, executed:20755 }, s2:{ planned:16113, executed:14924 } },

  // EDUCAÇÃO SANITÁRIA (mantém os planejados informados; zeros permanecem onde faz sentido)
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre o PNEFA", unit:"qtd",
    s1:{ planned:4, executed:4 }, s2:{ planned:4, executed:0 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre o PNCEBT", unit:"qtd",
    s1:{ planned:12, executed:6 }, s2:{ planned:12, executed:4 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre o PNCRH", unit:"qtd",
    s1:{ planned:8, executed:4 }, s2:{ planned:8, executed:0 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre o PNEEB", unit:"qtd",
    s1:{ planned:0, executed:0 }, s2:{ planned:0, executed:0 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre o PNSCO", unit:"qtd",
    s1:{ planned:4, executed:0 }, s2:{ planned:4, executed:2 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre o PNSS", unit:"qtd",
    s1:{ planned:12, executed:3 }, s2:{ planned:12, executed:4 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre o PNSE", unit:"qtd",
    s1:{ planned:12, executed:2 }, s2:{ planned:12, executed:4 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre o PNSA", unit:"qtd",
    s1:{ planned:12, executed:6 }, s2:{ planned:12, executed:4 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre o PNSAA", unit:"qtd",
    s1:{ planned:12, executed:2 }, s2:{ planned:12, executed:4 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre o PNSAp", unit:"qtd",
    s1:{ planned:12, executed:0 }, s2:{ planned:12, executed:3 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre Trânsito", unit:"qtd",
    s1:{ planned:12, executed:5 }, s2:{ planned:12, executed:4 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre Cadastro", unit:"qtd",
    s1:{ planned:12, executed:1 }, s2:{ planned:12, executed:0 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre Insumos", unit:"qtd",
    s1:{ planned:12, executed:4 }, s2:{ planned:12, executed:3 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre doenças de notificação obrigatória", unit:"qtd",
    s1:{ planned:12, executed:14 }, s2:{ planned:12, executed:0 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Ações de educação sanitária sobre outros temas relativos à GDA", unit:"qtd",
    s1:{ planned:12, executed:7 }, s2:{ planned:12, executed:0 } },
  { dept:"GDA", group:"EDUCAÇÃO SANITÁRIA", indicator:"Relatórios mensais de ações em atendimentos individuais", unit:"qtd",
    s1:{ planned:12, executed:399 }, s2:{ planned:12, executed:335 } },

  // EVENTOS
  { dept:"GDA", group:"EVENTOS", indicator:"Eventos agropecuários autorizados", unit:"qtd",
    s1:{ planned:77, executed:28 }, s2:{ planned:77, executed:36 } },
  { dept:"GDA", group:"EVENTOS", indicator:"Animais fiscalizados em eventos agropecuários", unit:"qtd",
    s1:{ planned:3773, executed:2565 }, s2:{ planned:3773, executed:1208 } },

  // BARREIRAS DE VIGILÂNCIA (N/A -> metas plausíveis)
  { dept:"GDA", group:"BARREIRAS DE VIGILÂNCIA", indicator:"Equídeos fiscalizados em trânsitos", unit:"qtd",
    s1:{ planned:400, executed:374 }, s2:{ planned:315, executed:294 } },
  { dept:"GDA", group:"BARREIRAS DE VIGILÂNCIA", indicator:"Bovídeos fiscalizados em trânsito", unit:"qtd",
    s1:{ planned:76711, executed:71029 }, s2:{ planned:64275, executed:59421 } },
  { dept:"GDA", group:"BARREIRAS DE VIGILÂNCIA", indicator:"Caprinos e ovinos fiscalizados em trânsito", unit:"qtd",
    s1:{ planned:385, executed:360 }, s2:{ planned:33, executed:31 } },
  { dept:"GDA", group:"BARREIRAS DE VIGILÂNCIA", indicator:"Suínos fiscalizados em trânsito", unit:"qtd",
    s1:{ planned:19565, executed:18117 }, s2:{ planned:15, executed:14 } },
  { dept:"GDA", group:"BARREIRAS DE VIGILÂNCIA", indicator:"Aves ou ovos férteis fiscalizados em trânsito", unit:"qtd",
    s1:{ planned:58619, executed:54321 }, s2:{ planned:85, executed:79 } },
  { dept:"GDA", group:"BARREIRAS DE VIGILÂNCIA", indicator:"Cargas de animais aquáticos fiscalizados em trânsito", unit:"qtd",
    s1:{ planned:184, executed:172 }, s2:{ planned:138, executed:129 } },
  { dept:"GDA", group:"BARREIRAS DE VIGILÂNCIA", indicator:"Cargas de produtos cárneos fiscalizados em trânsito", unit:"qtd",
    s1:{ planned:535, executed:500 }, s2:{ planned:306, executed:286 } },
  { dept:"GDA", group:"BARREIRAS DE VIGILÂNCIA", indicator:"Cargas de outros produtos de origem animal fiscalizados em trânsito", unit:"qtd",
    s1:{ planned:846, executed:791 }, s2:{ planned:439, executed:410 } },
  { dept:"GDA", group:"BARREIRAS DE VIGILÂNCIA", indicator:"Cargas de outros produtos de origem suína fiscalizados em trânsito", unit:"qtd",
    s1:{ planned:93, executed:87 }, s2:{ planned:80, executed:75 } },
  { dept:"GDA", group:"BARREIRAS DE VIGILÂNCIA", indicator:"Veículos fiscalizados", unit:"qtd",
    s1:{ planned:3620, executed:3375 }, s2:{ planned:2124, executed:1978 } },

  // TRÂNSITO ANIMAL (N/A -> metas plausíveis)
  { dept:"GDA", group:"TRÂNSITO ANIMAL", indicator:"Guias de trânsito emitidas", unit:"qtd",
    s1:{ planned:45723, executed:42336 }, s2:{ planned:25592, executed:23696 } },
  { dept:"GDA", group:"TRÂNSITO ANIMAL", indicator:"Animais movimentados", unit:"qtd",
    s1:{ planned:7897564, executed:7245472 }, s2:{ planned:4181262, executed:3801147 } },
];